# /home/ec2-user/docker-compose.yml

version: '3.7'

services:
  # Database
  docker_example_postgresql:
    image: postgres:13
    container_name: docker_example_postgresql
    environment:
      POSTGRES_USER: 'postgres_user'
      POSTGRES_PASSWORD: 'secure_password_123'
      POSTGRES_DB: 'postgres_db'
    networks:
      - docker_example_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres_user -d postgres_db']
      interval: 10s
      timeout: 5s
      retries: 5

  # Webserver (UI)
  docker_example_webserver:
    image: 503561425608.dkr.ecr.ca-central-1.amazonaws.com/severed/optics/strategy-1:latest
    entrypoint:
      - dagster-webserver
      - -h
      - '0.0.0.0'
      - -p
      - '3000'
      - -w
      - /opt/dagster/dagster_home/workspace.yaml # Use absolute path to be safe
    container_name: docker_example_webserver
    ports:
      - '3000:3000'
    environment:
      DAGSTER_HOME: /opt/dagster/dagster_home
      DAGSTER_POSTGRES_USER: 'postgres_user'
      DAGSTER_POSTGRES_PASSWORD: 'secure_password_123'
      DAGSTER_POSTGRES_DB: 'postgres_db'
      AWS_DEFAULT_REGION: ca-central-1
      AWS_REGION: ca-central-1
    volumes:
      - /home/ec2-user/dagster_home/dagster.yaml:/opt/dagster/dagster_home/dagster.yaml
      - /home/ec2-user/dagster_home/workspace.yaml:/opt/dagster/dagster_home/workspace.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - docker_example_network
    depends_on:
      docker_example_postgresql:
        condition: service_healthy

  # Daemon (Scheduler)
  docker_example_daemon:
    image: 503561425608.dkr.ecr.ca-central-1.amazonaws.com/severed/optics/strategy-1:latest
    entrypoint:
      - dagster-daemon
      - run
      - -w
      - /opt/dagster/dagster_home/workspace.yaml
    container_name: docker_example_daemon
    restart: always
    environment:
      DAGSTER_HOME: /opt/dagster/dagster_home
      AWS_DEFAULT_REGION: ca-central-1
      DAGSTER_POSTGRES_USER: 'postgres_user'
      DAGSTER_POSTGRES_PASSWORD: 'secure_password_123'
      DAGSTER_POSTGRES_DB: 'postgres_db'
    volumes:
      - /home/ec2-user/dagster_home/dagster.yaml:/opt/dagster/dagster_home/dagster.yaml
      - /home/ec2-user/dagster_home/workspace.yaml:/opt/dagster/dagster_home/workspace.yaml
    networks:
      - docker_example_network
    depends_on:
      docker_example_postgresql:
        condition: service_healthy

networks:
  docker_example_network:
    driver: bridge

volumes:
  postgres_data: